# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sex',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
